name: Publish (manual)
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('.changeset/*.md') != '' }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pnpm/action-setup@v3
        with: { version: 8.15.4 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: pnpm changeset version
      - run: pnpm changeset publish --no-git-tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
