name: Changesets - Create/Update Release PR
on:
  push:
    branches: [main]
    paths:
      - ".changeset/*.md"
permissions:
  contents: write
  pull-requests: write
jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('.changeset/*.md') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 8.15.4 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install --frozen-lockfile
      - name: Create or update release PR
        uses: changesets/action@v1
        with:
          publish: false
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
